mv -vf berkeley-softfloat-3/source/s_compare96M.c .
mv -vf berkeley-softfloat-3/source/s_compare128M.c .
mv -vf berkeley-softfloat-3/source/s_shortShiftLeft64To96M.c .
mv -vf berkeley-softfloat-3/source/s_shortShiftLeftM.c .
mv -vf berkeley-softfloat-3/source/s_shiftLeftM.c .
mv -vf berkeley-softfloat-3/source/s_shortShiftRightM.c .
mv -vf berkeley-softfloat-3/source/s_shortShiftRightJam64.c .
mv -vf berkeley-softfloat-3/source/s_shortShiftRightJamM.c .
mv -vf berkeley-softfloat-3/source/s_shiftRightJam32.c .
mv -vf berkeley-softfloat-3/source/s_shiftRightJam64.c .
mv -vf berkeley-softfloat-3/source/s_shiftRightJamM.c .
mv -vf berkeley-softfloat-3/source/s_shiftRightM.c .
mv -vf berkeley-softfloat-3/source/s_countLeadingZeros8.c .
mv -vf berkeley-softfloat-3/source/s_countLeadingZeros16.c .
mv -vf berkeley-softfloat-3/source/s_countLeadingZeros32.c .
mv -vf berkeley-softfloat-3/source/s_countLeadingZeros64.c .
mv -vf berkeley-softfloat-3/source/s_addM.c .
mv -vf berkeley-softfloat-3/source/s_addCarryM.c .
mv -vf berkeley-softfloat-3/source/s_addComplCarryM.c .
mv -vf berkeley-softfloat-3/source/s_negXM.c .
mv -vf berkeley-softfloat-3/source/s_sub1XM.c .
mv -vf berkeley-softfloat-3/source/s_subM.c .
mv -vf berkeley-softfloat-3/source/s_mul64To128M.c .
mv -vf berkeley-softfloat-3/source/s_mul128MTo256M.c .
mv -vf berkeley-softfloat-3/source/s_approxRecip_1Ks.c .
mv -vf berkeley-softfloat-3/source/s_approxRecip32_1.c .
mv -vf berkeley-softfloat-3/source/s_approxRecipSqrt_1Ks.c .
mv -vf berkeley-softfloat-3/source/s_approxRecipSqrt32_1.c .
mv -vf berkeley-softfloat-3/source/s_remStepMBy32.c .
mv -vf berkeley-softfloat-3/source/s_roundToUI32.c .
mv -vf berkeley-softfloat-3/source/s_roundMToUI64.c .
mv -vf berkeley-softfloat-3/source/s_roundToI32.c .
mv -vf berkeley-softfloat-3/source/s_roundMToI64.c .
mv -vf berkeley-softfloat-3/source/s_normSubnormalF16Sig.c .
mv -vf berkeley-softfloat-3/source/s_roundPackToF16.c .
mv -vf berkeley-softfloat-3/source/s_normRoundPackToF16.c .
mv -vf berkeley-softfloat-3/source/s_addMagsF16.c .
mv -vf berkeley-softfloat-3/source/s_subMagsF16.c .
mv -vf berkeley-softfloat-3/source/s_mulAddF16.c .
mv -vf berkeley-softfloat-3/source/s_normSubnormalF32Sig.c .
mv -vf berkeley-softfloat-3/source/s_roundPackToF32.c .
mv -vf berkeley-softfloat-3/source/s_normRoundPackToF32.c .
mv -vf berkeley-softfloat-3/source/s_addMagsF32.c .
mv -vf berkeley-softfloat-3/source/s_subMagsF32.c .
mv -vf berkeley-softfloat-3/source/s_mulAddF32.c .
mv -vf berkeley-softfloat-3/source/s_normSubnormalF64Sig.c .
mv -vf berkeley-softfloat-3/source/s_roundPackToF64.c .
mv -vf berkeley-softfloat-3/source/s_normRoundPackToF64.c .
mv -vf berkeley-softfloat-3/source/s_addMagsF64.c .
mv -vf berkeley-softfloat-3/source/s_subMagsF64.c .
mv -vf berkeley-softfloat-3/source/s_mulAddF64.c .
mv -vf berkeley-softfloat-3/source/s_tryPropagateNaNExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_invalidExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_normExtF80SigM.c .
mv -vf berkeley-softfloat-3/source/s_roundPackMToExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_normRoundPackMToExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_addExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_compareNonnormExtF80M.c .
mv -vf berkeley-softfloat-3/source/s_isNaNF128M.c .
mv -vf berkeley-softfloat-3/source/s_tryPropagateNaNF128M.c .
mv -vf berkeley-softfloat-3/source/s_invalidF128M.c .
mv -vf berkeley-softfloat-3/source/s_shiftNormSigF128M.c .
mv -vf berkeley-softfloat-3/source/s_roundPackMToF128M.c .
mv -vf berkeley-softfloat-3/source/s_normRoundPackMToF128M.c .
mv -vf berkeley-softfloat-3/source/s_addF128M.c .
mv -vf berkeley-softfloat-3/source/s_mulAddF128M.c .
mv -vf berkeley-softfloat-3/source/softfloat_state.c .
mv -vf berkeley-softfloat-3/source/ui32_to_f16.c .
mv -vf berkeley-softfloat-3/source/ui32_to_f32.c .
mv -vf berkeley-softfloat-3/source/ui32_to_f64.c .
mv -vf berkeley-softfloat-3/source/ui32_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/ui32_to_f128M.c .
mv -vf berkeley-softfloat-3/source/ui64_to_f16.c .
mv -vf berkeley-softfloat-3/source/ui64_to_f32.c .
mv -vf berkeley-softfloat-3/source/ui64_to_f64.c .
mv -vf berkeley-softfloat-3/source/ui64_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/ui64_to_f128M.c .
mv -vf berkeley-softfloat-3/source/i32_to_f16.c .
mv -vf berkeley-softfloat-3/source/i32_to_f32.c .
mv -vf berkeley-softfloat-3/source/i32_to_f64.c .
mv -vf berkeley-softfloat-3/source/i32_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/i32_to_f128M.c .
mv -vf berkeley-softfloat-3/source/i64_to_f16.c .
mv -vf berkeley-softfloat-3/source/i64_to_f32.c .
mv -vf berkeley-softfloat-3/source/i64_to_f64.c .
mv -vf berkeley-softfloat-3/source/i64_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/i64_to_f128M.c .
mv -vf berkeley-softfloat-3/source/f16_to_ui32.c .
mv -vf berkeley-softfloat-3/source/f16_to_ui64.c .
mv -vf berkeley-softfloat-3/source/f16_to_i32.c .
mv -vf berkeley-softfloat-3/source/f16_to_i64.c .
mv -vf berkeley-softfloat-3/source/f16_to_ui32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f16_to_ui64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f16_to_i32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f16_to_i64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f16_to_f32.c .
mv -vf berkeley-softfloat-3/source/f16_to_f64.c .
mv -vf berkeley-softfloat-3/source/f16_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/f16_to_f128M.c .
mv -vf berkeley-softfloat-3/source/f16_roundToInt.c .
mv -vf berkeley-softfloat-3/source/f16_add.c .
mv -vf berkeley-softfloat-3/source/f16_sub.c .
mv -vf berkeley-softfloat-3/source/f16_mul.c .
mv -vf berkeley-softfloat-3/source/f16_mulAdd.c .
mv -vf berkeley-softfloat-3/source/f16_div.c .
mv -vf berkeley-softfloat-3/source/f16_rem.c .
mv -vf berkeley-softfloat-3/source/f16_sqrt.c .
mv -vf berkeley-softfloat-3/source/f16_eq.c .
mv -vf berkeley-softfloat-3/source/f16_le.c .
mv -vf berkeley-softfloat-3/source/f16_lt.c .
mv -vf berkeley-softfloat-3/source/f16_eq_signaling.c .
mv -vf berkeley-softfloat-3/source/f16_le_quiet.c .
mv -vf berkeley-softfloat-3/source/f16_lt_quiet.c .
mv -vf berkeley-softfloat-3/source/f16_isSignalingNaN.c .
mv -vf berkeley-softfloat-3/source/f32_to_ui32.c .
mv -vf berkeley-softfloat-3/source/f32_to_ui64.c .
mv -vf berkeley-softfloat-3/source/f32_to_i32.c .
mv -vf berkeley-softfloat-3/source/f32_to_i64.c .
mv -vf berkeley-softfloat-3/source/f32_to_ui32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f32_to_ui64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f32_to_i32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f32_to_i64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f32_to_f16.c .
mv -vf berkeley-softfloat-3/source/f32_to_f64.c .
mv -vf berkeley-softfloat-3/source/f32_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/f32_to_f128M.c .
mv -vf berkeley-softfloat-3/source/f32_roundToInt.c .
mv -vf berkeley-softfloat-3/source/f32_add.c .
mv -vf berkeley-softfloat-3/source/f32_sub.c .
mv -vf berkeley-softfloat-3/source/f32_mul.c .
mv -vf berkeley-softfloat-3/source/f32_mulAdd.c .
mv -vf berkeley-softfloat-3/source/f32_div.c .
mv -vf berkeley-softfloat-3/source/f32_rem.c .
mv -vf berkeley-softfloat-3/source/f32_sqrt.c .
mv -vf berkeley-softfloat-3/source/f32_eq.c .
mv -vf berkeley-softfloat-3/source/f32_le.c .
mv -vf berkeley-softfloat-3/source/f32_lt.c .
mv -vf berkeley-softfloat-3/source/f32_eq_signaling.c .
mv -vf berkeley-softfloat-3/source/f32_le_quiet.c .
mv -vf berkeley-softfloat-3/source/f32_lt_quiet.c .
mv -vf berkeley-softfloat-3/source/f32_isSignalingNaN.c .
mv -vf berkeley-softfloat-3/source/f64_to_ui32.c .
mv -vf berkeley-softfloat-3/source/f64_to_ui64.c .
mv -vf berkeley-softfloat-3/source/f64_to_i32.c .
mv -vf berkeley-softfloat-3/source/f64_to_i64.c .
mv -vf berkeley-softfloat-3/source/f64_to_ui32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f64_to_ui64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f64_to_i32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f64_to_i64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f64_to_f16.c .
mv -vf berkeley-softfloat-3/source/f64_to_f32.c .
mv -vf berkeley-softfloat-3/source/f64_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/f64_to_f128M.c .
mv -vf berkeley-softfloat-3/source/f64_roundToInt.c .
mv -vf berkeley-softfloat-3/source/f64_add.c .
mv -vf berkeley-softfloat-3/source/f64_sub.c .
mv -vf berkeley-softfloat-3/source/f64_mul.c .
mv -vf berkeley-softfloat-3/source/f64_mulAdd.c .
mv -vf berkeley-softfloat-3/source/f64_div.c .
mv -vf berkeley-softfloat-3/source/f64_rem.c .
mv -vf berkeley-softfloat-3/source/f64_sqrt.c .
mv -vf berkeley-softfloat-3/source/f64_eq.c .
mv -vf berkeley-softfloat-3/source/f64_le.c .
mv -vf berkeley-softfloat-3/source/f64_lt.c .
mv -vf berkeley-softfloat-3/source/f64_eq_signaling.c .
mv -vf berkeley-softfloat-3/source/f64_le_quiet.c .
mv -vf berkeley-softfloat-3/source/f64_lt_quiet.c .
mv -vf berkeley-softfloat-3/source/f64_isSignalingNaN.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_ui32.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_ui64.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_i32.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_i64.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_ui32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_ui64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_i32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_i64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_f16.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_f32.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_f64.c .
mv -vf berkeley-softfloat-3/source/extF80M_to_f128M.c .
mv -vf berkeley-softfloat-3/source/extF80M_roundToInt.c .
mv -vf berkeley-softfloat-3/source/extF80M_add.c .
mv -vf berkeley-softfloat-3/source/extF80M_sub.c .
mv -vf berkeley-softfloat-3/source/extF80M_mul.c .
mv -vf berkeley-softfloat-3/source/extF80M_div.c .
mv -vf berkeley-softfloat-3/source/extF80M_rem.c .
mv -vf berkeley-softfloat-3/source/extF80M_sqrt.c .
mv -vf berkeley-softfloat-3/source/extF80M_eq.c .
mv -vf berkeley-softfloat-3/source/extF80M_le.c .
mv -vf berkeley-softfloat-3/source/extF80M_lt.c .
mv -vf berkeley-softfloat-3/source/extF80M_eq_signaling.c .
mv -vf berkeley-softfloat-3/source/extF80M_le_quiet.c .
mv -vf berkeley-softfloat-3/source/extF80M_lt_quiet.c .
mv -vf berkeley-softfloat-3/source/f128M_to_ui32.c .
mv -vf berkeley-softfloat-3/source/f128M_to_ui64.c .
mv -vf berkeley-softfloat-3/source/f128M_to_i32.c .
mv -vf berkeley-softfloat-3/source/f128M_to_i64.c .
mv -vf berkeley-softfloat-3/source/f128M_to_ui32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f128M_to_ui64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f128M_to_i32_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f128M_to_i64_r_minMag.c .
mv -vf berkeley-softfloat-3/source/f128M_to_f16.c .
mv -vf berkeley-softfloat-3/source/f128M_to_f32.c .
mv -vf berkeley-softfloat-3/source/f128M_to_f64.c .
mv -vf berkeley-softfloat-3/source/f128M_to_extF80M.c .
mv -vf berkeley-softfloat-3/source/f128M_roundToInt.c .
mv -vf berkeley-softfloat-3/source/f128M_add.c .
mv -vf berkeley-softfloat-3/source/f128M_sub.c .
mv -vf berkeley-softfloat-3/source/f128M_mul.c .
mv -vf berkeley-softfloat-3/source/f128M_mulAdd.c .
mv -vf berkeley-softfloat-3/source/f128M_div.c .
mv -vf berkeley-softfloat-3/source/f128M_rem.c .
mv -vf berkeley-softfloat-3/source/f128M_sqrt.c .
mv -vf berkeley-softfloat-3/source/f128M_eq.c .
mv -vf berkeley-softfloat-3/source/f128M_le.c .
mv -vf berkeley-softfloat-3/source/f128M_lt.c .
mv -vf berkeley-softfloat-3/source/f128M_eq_signaling.c .
mv -vf berkeley-softfloat-3/source/f128M_le_quiet.c .
mv -vf berkeley-softfloat-3/source/f128M_lt_quiet.c .
mv -vf berkeley-softfloat-3/source/8086/softfloat_raiseFlags.c .
mv -vf berkeley-softfloat-3/source/8086/s_f16UIToCommonNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_commonNaNToF16UI.c .
mv -vf berkeley-softfloat-3/source/8086/s_propagateNaNF16UI.c .
mv -vf berkeley-softfloat-3/source/8086/s_f32UIToCommonNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_commonNaNToF32UI.c .
mv -vf berkeley-softfloat-3/source/8086/s_propagateNaNF32UI.c .
mv -vf berkeley-softfloat-3/source/8086/s_f64UIToCommonNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_commonNaNToF64UI.c .
mv -vf berkeley-softfloat-3/source/8086/s_propagateNaNF64UI.c .
mv -vf berkeley-softfloat-3/source/8086/extF80M_isSignalingNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_extF80MToCommonNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_commonNaNToExtF80M.c .
mv -vf berkeley-softfloat-3/source/8086/s_propagateNaNExtF80M.c .
mv -vf berkeley-softfloat-3/source/8086/f128M_isSignalingNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_f128MToCommonNaN.c .
mv -vf berkeley-softfloat-3/source/8086/s_commonNaNToF128M.c .
mv -vf berkeley-softfloat-3/source/8086/s_propagateNaNF128M.c .
mv -vf berkeley-softfloat-3/build/Linux-386-GCC/platform.h .
mv -vf berkeley-softfloat-3/source/8086/specialize.h .
mv -vf berkeley-softfloat-3/source/include/*.h .

